version: 1

labels:
  - label: 'documentation'
    type: 'pull_request'
    files:
      - doc/*
      - doc/**/*
      - data/conky*.conf

  - label: 'extras'
    type: 'pull_request'
    files:
      - extras/*
      - extras/**/*

  - label: 'sources'
    type: 'pull_request'
    files:
      - src/*
      - src/**/*

  - label: 'tests'
    type: 'pull_request'
    files:
      - tests/**/*
      - tests/*

  - label: 'web'
    type: 'pull_request'
    files:
      - web/*
      - web/**/*

  - label: 'appimage'
    type: 'pull_request'
    files:
      - appimage/*
      - appimage/**/*

  - label: '3rdparty'
    type: 'pull_request'
    files:
      - 3rdparty/*
      - 3rdparty/**/*

  - label: 'gh-actions'
    type: 'pull_request'
    files:
      - .github/workflows/*
      - .github/workflows/**/*
      - .github/labeler.yml
      - .github/pull_request_template.md

  - label: 'dependencies'
    type: 'pull_request'
    files:
      - web/package-lock.json
      - cmake/ConkyPlatformChecks.cmake

  - label: 'audio'
    type: 'pull_request'
    files:
      - src/audacious.cc
      - src/audacious.h
      - src/cmus.cc
      - src/cmus.h
      - src/libmpdclient.cc
      - src/libmpdclient.h
      - src/mpd.cc
      - src/mpd.h
      - src/moc.cc
      - src/moc.h
      - src/mixer.cc
      - src/mixer.h
      - src/xmms2.cc
      - src/xmms2.h
      - src/pulseaudio.cc
      - src/pulseaudio.h

  - label: 'power'
    type: 'pull_request'
    files:
      - src/apcupsd.cc
      - src/apcupsd.h
      - src/bsdapm.cc
      - src/bsdapm.h
      - src/smapi.cc
      - src/smapi.h

  - label: 'display: console'
    type: 'pull_request'
    files:
      - src/display-console.cc
      - src/display-console.hh
  - label: 'display: file'
    type: 'pull_request'
    files:
      - src/display-file.cc
      - src/display-file.hh
  - label: 'display: http'
    type: 'pull_request'
    files:
      - src/display-http.cc
      - src/display-http.hh
  - label: 'display: ncurses'
    type: 'pull_request'
    files:
      - src/nc.cc
      - src/nc.h
      - src/display-ncurses.cc
      - src/display-ncurses.hh
  - label: 'display: wayland'
    type: 'pull_request'
    files:
      - src/wl.cc
      - src/wl.h
      - src/wlr-layer-shell-unstable-v1.xml
      - src/display-wayland.cc
      - src/display-wayland.hh
  - label: 'display: x11'
    type: 'pull_request'
    files:
      - src/x11-color.cc
      - src/x11-color.h
      - src/x11.cc
      - src/x11.h
      - src/display-x11.cc
      - src/display-x11.hh

  - label: 'build system'
    type: 'pull_request'
    files:
      - '**/CMakeLists.txt'
      - '*.cmake'

  - label: 'cairo'
    type: 'pull_request'
    files:
      - 'lua/*cairo*'

  - label: 'disk io'
    type: 'pull_request'
    files:
      - src/diskio.cc
      - src/diskio.h

  - label: 'cpu'
    type: 'pull_request'
    files:
      - src/cpu.cc
      - src/cpu.h
      - src/proc.cc
      - src/proc.h
      - src/top.cc
      - src/top.h

  - label: 'lua'
    type: 'pull_request'
    files:
      - lua/*
      - lua/**/*
      - src/llua.cc
      - src/llua.h
      - src/luamm.cc
      - src/luamm.h
      - src/lua-config.cc
      - src/lua-config.hh

  - label: 'os: linux'
    type: 'pull_request'
    files:
      - src/linux.cc
      - src/linux.h
  - label: 'os: dragonfly'
    type: 'pull_request'
    files:
      - src/dragonfly.cc
      - src/dragonfly.h
  - label: 'os: freebsd'
    type: 'pull_request'
    files:
      - src/freebsd.cc
      - src/freebsd.h
  - label: 'os: netbsd'
    type: 'pull_request'
    files:
      - src/netbsd.cc
      - src/netbsd.h
  - label: 'os: openbsd'
    type: 'pull_request'
    files:
      - src/openbsd.cc
      - src/openbsd.h
  - label: 'os: solaris'
    type: 'pull_request'
    files:
      - src/solaris.cc
      - src/solaris.h
  - label: 'os: haiku'
    type: 'pull_request'
    files:
      - src/haiku.cc
      - src/haiku.h

  - label: 'mouse events'
    type: 'pull_request'
    files:
      - src/scroll.cc
      - src/scroll.h
      - src/mouse-events.cc
      - src/mouse-events.h

  - label: 'networking'
    type: 'pull_request'
    files:
      - src/net_stat.cc
      - src/net_stat.h
      - src/tcp-portmon.cc
      - src/tcp-portmon.h
      - src/read_tcpip.cc
      - src/read_tcpip.h

  - label: 'nvidia'
    type: 'pull_request'
    files:
      - src/nvidia.cc
      - src/nvidia.h

  - label: 'rendering'
    type: 'pull_request'
    files:
      - src/text_object.cc
      - src/text_object.h
      - src/specials.cc
      - src/specials.h

  - label: 'text'
    type: 'pull_request'
    files:
      - src/text_object.cc
      - src/text_object.h
      - src/template.cc
      - src/template.h
      - src/tailhead.cc
      - src/tailhead.h
      - src/specials.cc
      - src/specials.h
