name: 'Pull Request Labeler'
on:
  - pull_request_target
  - issues

jobs:
  triage:
    permissions:
      contents: read
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Run labeler
        uses: srvaroa/labeler@v1
        env:
          GITHUB_TOKEN: '${{ secrets.GITHUB_TOKEN }}'
